#__Build
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src

ARG SHARED_LIB_NUGET_SOURCE_INDEX_URI
ARG SHARED_LIB_NUGET_SOURCE_NAME
ARG SHARED_LIB_NUGET_SOURCE_USER_NAME
ARG SHARED_LIB_NUGET_SOURCE_AUTH_TOKEN

ARG AUTHORIZATION_SERVICE_NUGET_SOURCE_INDEX_URI
ARG AUTHORIZATION_SERVICE_NUGET_SOURCE_NAME
ARG AUTHORIZATION_SERVICE_NUGET_SOURCE_USER_NAME
ARG AUTHORIZATION_SERVICE_NUGET_SOURCE_AUTH_TOKEN

COPY ["./src/BookStore.BookService.sln", "./"]

COPY ["./src/BookStore.BookService.AppEntryPoint/*.csproj", "./BookStore.BookService.AppEntryPoint/"]
COPY ["./src/BookStore.BookService.BL/*.csproj", "./BookStore.BookService.BL/"]
COPY ["./src/BookStore.BookService.Configs/*.csproj", "./BookStore.BookService.Configs/"]
COPY ["./src/BookStore.BookService.Contracts/*.csproj", "./BookStore.BookService.Contracts/"]
COPY ["./src/BookStore.BookService.Data/*.csproj", "./BookStore.BookService.Data/"]
COPY ["./src/BookStore.BookService.IntegrationTests/*.csproj", "./BookStore.BookService.IntegrationTests/"]
COPY ["./src/BookStore.BookService.Settings/*.csproj", "./BookStore.BookService.Settings/"]
COPY ["./src/BookStore.BookService.UnitTests/*.csproj", "./BookStore.BookService.UnitTests/"]
COPY ["./src/BookStore.BookService.WebEntryPoint/*.csproj", "./BookStore.BookService.WebEntryPoint/"]

RUN dotnet nuget add source $SHARED_LIB_NUGET_SOURCE_INDEX_URI --name $SHARED_LIB_NUGET_SOURCE_NAME --username $SHARED_LIB_NUGET_SOURCE_USER_NAME --password $SHARED_LIB_NUGET_SOURCE_AUTH_TOKEN --store-password-in-clear-text
RUN dotnet nuget add source $AUTHORIZATION_SERVICE_NUGET_SOURCE_INDEX_URI --name $AUTHORIZATION_SERVICE_NUGET_SOURCE_NAME --username $AUTHORIZATION_SERVICE_NUGET_SOURCE_USER_NAME --password $AUTHORIZATION_SERVICE_NUGET_SOURCE_AUTH_TOKEN --store-password-in-clear-text

RUN dotnet restore /src/BookStore.BookService.sln

COPY ["./src/.", "./"]
WORKDIR /src/BookStore.BookService.AppEntryPoint
RUN dotnet publish -c release -o /published --no-restore

#__Release
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine

ARG ENVIRONMENT

ARG BOOK_STORE_SWAGGER_UI_CLIENT_ID
ARG BOOK_STORE_SWAGGER_UI_CLIENT_SECRET

ARG BOOK_SERVICE_DATABASE_CONNECTION_STRING

ARG MASSTRANSIT_URI
ARG MASSTRANSIT_HOST
ARG MASSTRANSIT_USER_NAME
ARG MASSTRANSIT_PASSWORD

ARG AUTHORIZATION_SERVICE_ISSUER
ARG AUTHORIZATION_SERVICE_TOKEN_URI
ARG AUTHORIZATION_SERVICE_SIGN_IN_URI

ENV ASPNETCORE_ENVIRONMENT=$ENVIRONMENT
ENV ASPNETCORE_URLS="http://+:80"

ENV APP_CONFIG__ENVIRONMENT=$ENVIRONMENT

ENV LOG_CONFIG__LOG_FILE_PATH="./logs/book-store.book-service.txt"
ENV LOG_CONFIG__OUTPUT_TEMPLATE="{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] [{SourceContext:l}] {Message}{NewLine}{Exception}"

ENV AUTHORIZATION_SERVICE_CONFIG__ISSUER=$AUTHORIZATION_SERVICE_ISSUER
ENV AUTHORIZATION_SERVICE_CONFIG__TOKEN_URI=$AUTHORIZATION_SERVICE_TOKEN_URI
ENV AUTHORIZATION_SERVICE_CONFIG__SIGN_IN_URI=$AUTHORIZATION_SERVICE_SIGN_IN_URI

ENV SWAGGER_CONFIG__UI__CLIENT_ID=$BOOK_STORE_SWAGGER_UI_CLIENT_ID
ENV SWAGGER_CONFIG__UI__CLIENT_SECRET=$BOOK_STORE_SWAGGER_UI_CLIENT_SECRET

ENV BASE_DATABASE_CONFIG__CONNECTION_STRING=$BOOK_SERVICE_DATABASE_CONNECTION_STRING

ENV MASSTRANSIT_CONFIG__URI=$MASSTRANSIT_URI
ENV MASSTRANSIT_CONFIG__HOST=$MASSTRANSIT_HOST
ENV MASSTRANSIT_CONFIG__USER_NAME=$MASSTRANSIT_USER_NAME
ENV MASSTRANSIT_CONFIG__PASSWORD=$MASSTRANSIT_PASSWORD

# ENV ASPNETCORE_ENVIRONMENT="Development"
# ENV ASPNETCORE_URLS="http://+:80"

# ENV SWAGGERUI_CLIENT_ID="SwaggerUI"
# ENV SWAGGERUI_CLIENT_SECRET="KmsleOF322(@4msl!!ols"

# ENV MASSTRANSIT_HOST="book-store"
# ENV MASSTRANSIT_USER_NAME="BookStore"
# ENV MASSTRANSIT_PASSWORD="KJiwjd2*12asl!"

# ENV MINIO_ACCESS_KEY="Admin"
# ENV MINIO_SECRET_KEY="Akwi@!@4j2"
# ENV MINIO_DEFAULT_BUCKET_NAME="root-bucket"

# ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
# RUN apk add icu-libs

# ENV MUSL_LOCPATH=/usr/local/share/i18n/locales/musl
# RUN apk add --update git cmake make musl-dev gcc gettext-dev libintl
# RUN cd /tmp && git clone https://github.com/rilian-la-te/musl-locales.git
# RUN cd /tmp/musl-locales && cmake . && make && make install

# ENV LANG=ru_RU.UTF-8
# ENV LANGUAGE=ru_RU.UTF-8
# ENV LC_ALL=ru_RU.UTF-8
#___________________________
WORKDIR /BookStore.BookService
COPY --from=build /published ./
ENTRYPOINT ["dotnet", "BookStore.BookService.AppEntryPoint.dll"]